### ISSUE TITLE
DevOps - Add a Test GitHub Action for CI or Future DevGrid Testing Hook

### ISSUE THREAD

**Issue by paulwconnor-ai** [robotick-labs/robotick-engine#50]
## 📌 Ticket: DevOps - Add a Test GitHub Action for CI or Future DevGrid Testing Hook

**Goal:**  
Create a basic GitHub Action that verifies our infrastructure is working correctly for CI. This action will serve as a placeholder and diagnostic hook, and can later be extended to trigger full DevGrid-based hardware tests via a secure cloud-queueing mechanism (e.g., via DynamoDB + local test agent polling).

---

### 🛠️ Tasks

- [ ] Define a minimal GitHub Actions workflow YAML file (`.github/workflows/test_ci.yml`)
- [ ] Run a trivial CI step (e.g., `echo "Hello from CI"` or `build/test Robotick`)
- [ ] Add a job output artifact (e.g., simple log file or timestamp) to verify upload works
- [ ] Add optional label-based trigger logic (e.g. run only on PRs with `ci/test` label)
- [ ] Structure the action to allow easy extension:
  - Insert a stub step like `# TODO: Call DevGrid queue API`
  - Add basic scaffolding to post a JSON payload to a REST endpoint (mocked for now)

---

### 💡 Rationale

This test action will serve multiple purposes:
- Confirm our GitHub Actions setup is valid and functioning
- Provide a predictable test hook for pipeline diagnostics
- Lay the groundwork for future integration with our secure DevGrid hardware test infrastructure (pull-based agents polling for jobs)
- Reduce risk of regression in the DevOps layer over time

---

### 🔮 Future Integration (DevGrid)

Longer-term, this GitHub Action will:
- Push test jobs (e.g., `run-stm32-tests`) to a secure intermediary such as DynamoDB via REST
- Poll for and display job results (test verdicts, logs) returned by local agents
- Allow hardware-in-the-loop testing without exposing any runner or MCU device to the public internet

---

### 📁 File to Create

```bash
.github/workflows/test_ci.yml
```

Example stub:

```yaml
name: CI Test Hook

on:
  push:
    branches: [dev]
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions CI!"

      # TODO: Call DevGrid endpoint to enqueue remote hardware test
      - name: (Future) Trigger DevGrid test
        run: echo "Triggering hardware test (stubbed for now)"

      - name: Save artifact
        run: echo "This is a test artifact" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-artifact
          path: artifact.txt
```
